export const catAndSub = {
  "Staples": [
    "Atta, Flours and Sooji",
    "Dal and Pulses",
    "Rice and Rice Products",
    "Edible oils",
    "Masala and Spices",
    "Salt, Sugar and Jaggery",
    "Soya Products, Wheat and others",
    "Dry fruits and nuts",
  ],
  "Snacks and branded foods": [
    "Biscuits and cookies",
    "Noodle, Pasta and Vermicelli",
    "Breakfast cereals",
    "Snacks and namkeen",
    "Chocolates and candies",
    "Ready to cook and eat",
    "Frozen veggies and snacks",
    "Spread, sauces and ketchup",
    "Indian sweets",
    "Pickles and chutneys",
  ],
  Beverages: [
    "Tea",
    "Coffee",
    "Fruit juices",
    "Energy and soft drinks",
    "Health drinks and supplement",
    "Soda and flavoured water",
  ],
  "Personal care": [
    "Hair care",
    "Oral care",
    "Bath and hand wash",
    "Body wash and bathing accessories",
    "Feminine Hygiene",
    "Men's grooming",
    "Deo and Fragrances",
    "Health and wellness",
    "Skin care",
  ],
  "Meal": [
    "Veg",
    "Non-Veg",
  ],
};
