export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const RAZORPAY_ORDER_REQUEST = "RAZORPAY_ORDER_REQUEST";
export const RAZORPAY_ORDER_SUCCESS = "RAZORPAY_ORDER_SUCCESS";
export const RAZORPAY_ORDER_FAIL = "RAZORPAY_ORDER_FAIL";

export const VERIFY_PAYMENT_REQUEST = "VERIFY_PAYMENT_REQUEST";
export const VERIFY_PAYMENT_SUCCESS = "VERIFY_PAYMENT_SUCCESS";
export const VERIFY_PAYMENT_FAIL = "VERIFY_PAYMENT_FAIL";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const ORDER_ALL_MY_REQUEST = "ORDER_ALL_MY_REQUEST";
export const ORDER_ALL_MY_SUCCESS = "ORDER_ALL_MY_SUCCESS";
export const ORDER_ALL_MY_FAIL = "ORDER_ALL_MY_FAIL";
