export const SELLER_LOGIN_REQUEST = "SELLER_LOGIN_REQUEST";
export const SELLER_LOGIN_SUCCESS = "SELLER_LOGIN_SUCCESS";
export const SELLER_LOGIN_FAIL = "SELLER_LOGIN_FAIL";
export const SELLER_LOGOUT = "SELLER_LOGOUT";

export const SELLER_REGISTER_REQUEST = "SELLER_REGISTER_REQUEST";
export const SELLER_REGISTER_SUCCESS = "SELLER_REGISTER_SUCCESS";
export const SELLER_REGISTER_FAIL = "SELLER_REGISTER_FAIL";

export const SELLER_ADD_PRODUCT_REQUEST = "SELLER_ADD_PRODUCT_REQUEST";
export const SELLER_ADD_PRODUCT_SUCCESS = "SELLER_ADD_PRODUCT_SUCCESS";
export const SELLER_ADD_PRODUCT_FAIL = "SELLER_ADD_PRODUCT_FAIL";

export const SELLER_PRODUCT_FILTER_REQUEST = "SELLER_PRODUCT_FILTER_REQUEST";
export const SELLER_PRODUCT_FILTER_SUCCESS = "SELLER_PRODUCT_FILTER_SUCCESS";
export const SELLER_PRODUCT_FILTER_FAIL = "SELLER_PRODUCT_FILTER_FAIL";

export const SELLER_GET_ORDERS_REQUEST = "SELLER_GET_ORDERS_REQUEST";
export const SELLER_GET_ORDERS_SUCCESS = "SELLER_GET_ORDERS_SUCCESS";
export const SELLER_GET_ORDERS_FAIL = "SELLER_GET_ORDERS_FAIL";

export const ORDER_ACCEPT_REQUEST = "ORDER_ACCEPT_REQUEST";
export const ORDER_ACCEPT_SUCCESS = "ORDER_ACCEPT_SUCCESS";
export const ORDER_ACCEPT_FAIL = "ORDER_ACCEPT_FAIL";

export const ORDER_SHIP_REQUEST = "ORDER_SHIP_REQUEST";
export const ORDER_SHIP_SUCCESS = "ORDER_SHIP_SUCCESS";
export const ORDER_SHIP_FAIL = "ORDER_SHIP_FAIL";

export const ORDER_DELIVER_REQUEST = "ORDER_DELIVER_REQUEST";
export const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS";
export const ORDER_DELIVER_FAIL = "ORDER_DELIVER_FAIL";

export const SELLER_GET_ORDER_DETAILS_REQUEST =
  "SELLER_GET_ORDER_DETAILS_REQUEST";
export const SELLER_GET_ORDER_DETAILS_SUCCESS =
  "SELLER_GET_ORDER_DETAILS_SUCCESS";
export const SELLER_GET_ORDER_DETAILS_FAIL = "SELLER_GET_ORDER_DETAILS_FAIL";
